FROM node:16.13-alpine

# Dependencies
RUN apk add --no-cache ca-certificates git

# [Optional] Uncomment if you want to install more global node packages
# RUN su node -c "npm install -g <your-package-list -here>"
